# Generated by Django 3.0.5 on 2020-07-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saabtopia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Descritpion'),
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Descritpion'),
        ),
        migrations.AddField(
            model_name='producent',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Descritpion'),
        ),
        migrations.AddField(
            model_name='usercar',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Descritpion'),
        ),
    ]
