# Generated by Django 3.0.5 on 2020-07-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saabtopia', '0002_auto_20200728_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producent',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
